#!/bin/bash
# $Id: Eth2Bond,v 1.1 2015/01/07 16:28:45 root Exp $
# This tool will convert ethX interfaces to bondX interfaces.
SYSCFG_DIR=/etc/sysconfig/network-scripts
TMPCFG_DIR=/var/tmp/eth2bond
DEF_BONDING_OPTS="'resend_igmp=2 mode=active-backup miimon=100'"

[ -d ${TMPCFG_DIR} ] || mkdir -pv ${TMPCFG_DIR}

for	myeth in ${SYSCFG_DIR}/ifcfg-eth[0-9]*
do
	/bin/echo "(II) Processing ${myeth}..."
	i="$(basename ${myeth}|sed -e 's/ifcfg.eth//')"
	TGT_ETH="${TMPCFG_DIR}/ifcfg-eth${i}"
	TGT_BOND="${TMPCFG_DIR}/ifcfg-bond${i}"
	/bin/echo "(II) Saved copy of ${myeth} to ${TGT_ETH}.orig"
	/bin/cp -pf ${myeth} ${TGT_ETH}.orig

	/bin/echo "(II) Building ${TGT_ETH} from ${myeth}..."
	/bin/echo -e "DEVICE=eth${i}\nSLAVE=yes\nMASTER=bond${i}\nTYPE=Ethernet\nNM_CONTROLLED='no'\nBOOTPROTO=static" > ${TGT_ETH}
	/bin/egrep "^(ONBOOT|HWADDR|ETHTOOL_OPTS)" ${myeth} >> ${TGT_ETH}

	/bin/echo "(II) Building ${TGT_BOND} from ${myeth}..."
	/bin/echo -e "DEVICE=bond${i}\nTYPE=Bond\nNM_CONTROLLED='no'\nBOOTPROTO=static" > ${TGT_BOND}
	/bin/egrep "^(ONBOOT|IPADDR|NETMASK|GATEWAY|BROADCAST)" ${myeth} >> ${TGT_BOND}
	/bin/echo "BONDING_OPTS=${DEF_BONDING_OPTS}" >> ${TGT_BOND}
	/bin/echo ""
done

