#!/bin/bash
#
# $Id: lseth,v 1.16 2015/02/11 23:12:24 root Exp $
#
PHYS_PRINT_PATTERN="%-6s%8s%8s %-10s%-14s%-21s%-20s%s\n"
VIRT_PRINT_PATTERN="%-6s%16s %-24s%-19s%-20s%s\n"

# Sanity Check
if [ "x$(uname -s)" != "xLinux" ]; then
	echo "Not supported on $(uname -s)! Exit!"
	exit 127
fi

# Check for sort version
SORT_VER=$(sort --version|awk '{ if (($1 == "sort" ) && ($2 ~ /GNU/)) { ver=$4 } } END { if (ver != "") print ver ; else print 0 } '|cut -d. -f1)

if [ $SORT_VER -ge 8 ]; then
	SORT_CMD="sort -V"
else
	SORT_CMD="sort"
fi

# Header state
hstate=0

for mydev in $(ls -d /sys/class/net/eth* /sys/class/net/ib* 2> /dev/null|xargs -n1|${SORT_CMD})
do
	if [ "x${mydev}" != "x" ]; then
		HWPATH="${mydev}/device"
		SPEED="N/A"
		if [ -d ${HWPATH} ]; then
			if [ $hstate -eq 0 ]; then
				printf "\n${PHYS_PRINT_PATTERN}" "#PHYS" "STATE" "SPEED" "DRIVER" "HW_Path" "MAC_Addr" "IP_Addr" "Description"
				hstate+=1
			fi
			DEVI=$(basename ${mydev})
			STATE=$(/sbin/ip -o a l ${DEVI}|awk ' { if ($4 == "mtu") { if ($3 ~ /,UP,/ ) print "up"; else print "(down)" }}')
			if [ -f ${mydev}/speed -a "x${STATE}" = "xup" ]; then
				SPEED=$(cat ${mydev}/speed)
			else
				tmp=$(/sbin/ethtool ${DEVI} 2>/dev/null|awk '{ if (( $1 == "Speed:" ) && ( $2 ~ /Mb.s/ )) { print $2}}' |sed -e 's@Mb.s@@' )
				if [ "x${tmp}" != "x" ]; then
					SPEED=${tmp}
				fi
			fi
			case ${DEVI} in
				eth*)
					SWDRIVER=$(/sbin/ethtool -i ${DEVI} 2>/dev/null|awk '{ if ( $1 == "driver:" ) { print $2}}' )
					PCIPATH=$(/sbin/ethtool -i ${DEVI} 2>/dev/null|awk '{ if ( $1 == "bus-info:" ) { print $2}}' )
					if [ -f ${mydev}/address ]; then
						MCADDR=$(cat ${mydev}/address)
					else
						MCADDR=$(/sbin/ip a l ${DEVI}|awk '{ if ( $1 ~ /link.ether/ ) print $2 }')
					fi
					;;
				ib*)
					SWDRIVER=$(/sbin/ethtool -i ${DEVI} 2>/dev/null|awk '{ if ( $1 == "driver:" ) { print $2}}' )
					PCIPATH=$(/bin/ls -l ${HWPATH}|sed -e 's@.*/@@')
					if [ -f ${mydev}/address ]; then
						MCADDR=$(cat ${mydev}/address |sed -e 's/\(.*00:00:00:00:\)\(.*$\)/\2/')
					else
						MCADDR="N/A"
					fi
					;;
				*)
					;;
			esac
			# Catchall Software fallbacks
			if [ "x${SWDRIVER}" = "x" ]; then
				# This most likely means we're not root
				SWDRIVER=$(/bin/ls -l ${mydev}/device/driver/module 2>/dev/null|sed -e 's@.*/@@')
			fi
			if [ "x${PCIPATH}" = "x" ]; then
				# This most likely means we're not root
				PCIPATH=$(/bin/ls -l ${HWPATH}|sed -e 's@.*/@@')
			fi

			case ${SWDRIVER} in
				# For some drivers, there is often much info in the Subsystem field..
				ixgbe|sfc|e1000e|igb)
					MIN_DESCLEN=16
					DEV_VEND=$(/sbin/lspci -vmm -s ${PCIPATH} 2> /dev/null|grep '^SVendor'|cut -d: -f2|xargs)
					DEV_DESC=$(/sbin/lspci -vmm -s ${PCIPATH} 2> /dev/null|grep '^SDevice'|cut -d: -f2|xargs)
					if [ $(echo ${DEV_DESC}|wc -c) -ge ${MIN_DESCLEN} ]; then
						# Desc is long enough, let's try it
						DESC="${DEV_VEND} ${DEV_DESC}"
					else
						# Desc is too short, fall back
						DESC=$(/sbin/lspci -D -s ${PCIPATH} 2> /dev/null|sed -e 's@.*: @@' )
					fi
					;;
				*)
					DESC=$(/sbin/lspci -D -s ${PCIPATH} 2> /dev/null|sed -e 's@.*: @@' )
					;;
			esac

			IPADDR=$(/sbin/ip -4 a s ${DEVI}|awk '{ if (( $1 == "inet" ) && ( $6 == "global" ) && ( $7 != "secondary")) print $2}')
			if [ "x${IPADDR}" = "x" ]; then
				IPADDR="N/A"
			fi

			# Printout
			printf "${PHYS_PRINT_PATTERN}" "${DEVI}" "${STATE}" "${SPEED}" "${SWDRIVER}" "${PCIPATH}" "${MCADDR}" "${IPADDR}" "${DESC}"
		fi
	fi
done

# Header state
hstate=0
KREV=$(uname -r|cut -d- -f1)
case $KREV in
	2.6.18)
		VGLOB=/sys/class/net/bond
		;;
	2.6.32)
		VGLOB=/sys/devices/virtual/net/
		;;
	*)
		VGLOB=/sys/devices/virtual/net/
		;;
esac

for mydev in $(ls -d ${VGLOB}* 2> /dev/null |xargs -n1|${SORT_CMD})
do
	if [ "x${mydev}" != "x" ]; then
		HWTYPE="${mydev}/type"
		DEVI=$(basename ${mydev})
		if [ -f ${HWTYPE} ]; then
			if [ "x$(cat ${HWTYPE})" = "x1" ]; then
				if [ $hstate -eq 0 ]; then
					printf "\n${VIRT_PRINT_PATTERN}" "#VIRT" "STATE" "DRIVER" "MAC_Addr" "IP_Addr" "Description"
					hstate+=1
				fi
				STATE=$(cat ${mydev}/operstate)
				STATE=$(/sbin/ip -o a l ${DEVI}|awk ' { if ($4 == "mtu") { if ($3 ~ /,UP,/ ) print "up"; else print "(down)" }}')
				if [ -f ${mydev}/bonding/slaves ]; then
					SLAVES=$(cat ${mydev}/bonding/slaves)
					DESC="[ ${SLAVES} ]"
				else
					DESC="N/A"
				fi
				IPADDR=$(/sbin/ip -4 a s ${DEVI}|awk '{ if (( $1 == "inet" ) && ( $6 == "global" ) && ( $7 != "secondary")) print $2}')
				if [ "x${IPADDR}" = "x" ]; then
					IPADDR="N/A"
				fi
				MCADDR=$(/sbin/ip a l ${DEVI}|awk '{ if ( $1 ~ /link.ether/ ) print $2 }')
				tmpdrv=$(echo ${DEVI}|sed -e 's@[0-9]\{1,\}@@')
				case ${tmpdrv} in
					bond)
						tmpdrv=bonding
						;;
				esac
				drvver=$(/sbin/modinfo -F version ${tmpdrv} 2> /dev/null)
				if [ "x${drvver}" = "x" ]; then
					drvver=$(uname -r|sed -e 's@\.el.*@@')
				fi
				SWDRIVER="${tmpdrv} (${drvver})"

				# Printout
				printf "${VIRT_PRINT_PATTERN}" "${DEVI}" "${STATE}" "${SWDRIVER}" "${MCADDR}" "${IPADDR}" "${DESC}"
			fi
		fi
	fi
done

