#!/bin/bash
# $Id: lsthp,v 1.5 2019/04/03 21:17:33 root Exp $
#
PRINT_PATTERN="%-24s %-10s : %s %s\n"
typeset -i index=0

if [ $UID -ne 0 ]; then
	echo "Run $0 as root!" ; exit 127
fi

# Loop

nrindex=$(/bin/grep -s 'KernelPageSize:.*2048 kB' /proc/*/smaps|grep -v '0 kB$'|wc -l)
if [ ${nrindex} -eq 0 ]; then
	printf "No HugePages found!\n"
else
	if [ $index -eq 0 ]; then
		# Header
		printf "${PRINT_PATTERN}" "procname (2Mb HugePages)" "PID" "Size" "unit"
	fi

	(/bin/grep -B11 -s 'KernelPageSize:.*2048 kB' /proc/*/smaps| grep '/smaps.Size:'| \
		sed -e 's@/proc/@@' -e 's@/smaps.Size:@@' | \
		awk '{ print $2,$3,$1}'| \
		sort -n | \
		while read size unit pid
	do
		if [ -f /proc/${pid}/status ]; then
			pidname=$(grep -s 'Name:' /proc/${pid}/status|awk '{ print $2}')
			if [  "$pidname" = "qemu-kvm" ]; then
				guestname="$(strings -a /proc/${pid}/cmdline |grep -A1 -i '^-name'|sed -e 's@,debug.*@@' -e 's@guest=@@'|tail -1)"
				printf "${PRINT_PATTERN}" "${pidname} [ ${guestname} ]" "(${pid})" "${size}" "${unit}"
			else
				printf "${PRINT_PATTERN}" "${pidname}" "(${pid})" "${size}" "${unit}"
			fi
		fi
		index=1
	done)|sort -u
fi

