#!/bin/bash
# $Id: lsthp,v 1.1 2015/01/27 22:04:06 root Exp $
#
PRINT_PATTERN="%-24s : %s %s\n"

if [ $UID -ne 0 ]; then
	echo "Run $0 as root!" ; exit 127
fi

# Header
printf "${PRINT_PATTERN}" "procname (PID)" "Size" "unit"

# Loop
/bin/grep -s AnonHugePages /proc/*/smaps| \
	grep -v '0 kB$'| \
	sed -e 's@/proc/@@' -e 's@/smaps:AnonHugePages:@@' | \
	awk '{ print $2,$3,$1}'| \
	sort -n | \
	while read size unit pid
do
	if [ -f /proc/${pid}/status ]; then
		pidname=$(grep -s 'Name:' /proc/${pid}/status|awk '{ print $2}')
		printf "${PRINT_PATTERN}" "${pidname} (${pid})" "${size}" "${unit}"
	fi
done
